---
steps:
  - label: ":ruby: Render Test Matrix"
    timeout_in_minutes: 5
    env:
      RAILS_ENV: test
    plugins:
      - ssh://git@github.com/Invoca/invoca-ruby-test-matrix-buildkite-plugin.git#main:
          min_ruby_version: '3.1'
          slack_notification_channel: '#dev-team-call-interactions-thundercats'
          test_command: 'bundle exec rspec'
          queue_variant: mysql
