---
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/active_support-deprecation_test_helper: 'true'
  namespace: jenkins
  name: active_support-deprecation_test_helper
spec:
  containers:
  - name: ruby
    image: ruby:2.6.5
    tty: true
    resources:
      requests:
        memory: "100Mi"
    command:
      - cat
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    resources:
      requests:
        memory: "512Mi"
    env:
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"

